name = "reference"
subteam-of = "lang"

[people]
leads = ["Havvy"]
members = [
    "Centril",
    "ehuss",
    "Havvy",
    "matthewjasper",
]

[website]
name = "Reference team"
description = "Developing and writing the Rust reference"
